dependencies:
  - name: react
    version: 18.3.1
    src: www/lib/react
    script: react.production.min.js
  - name: react-dom
    version: 18.3.1
    src: www/lib/react-dom
    script: react-dom.production.min.js
  - name: dayjs
    version: 1.11.0
    src: www/lib/dayjs
    script: dayjs.min.js
  - name: antd-cssinjs
    version: 1.0.0
    src: www/lib/antd-cssinjs
    script: cssinjs.min.js
  - name: antd-icons
    version: 5.0.0
    src: www/lib/antd-icons
    script: index.umd.min.js
  - name: antd
    version: 5.0.0
    src: www/lib/antd
    script: antd.min.js
  - name: antdx
    version: 1.0.0
    src: www/lib/antdx
    script: antdx.min.js
  - name: x-sdk-vendor
    version: 0.2.0
    src: www
    script: vendor.js
  - name: sources
    version: 0.2.0
    src: www
    script: sources.js
